# Generated by Django 6.1.1 on 2026-09-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('client', models.CharField(blank=True, max_length=100)),
                ('industry', models.CharField(default='Technology & Retail', max_length=100)),
                ('category', models.CharField(choices=[('web', 'Web Application'), ('mobile', 'Mobile Application'), ('cloud', 'Cloud & DevOps'), ('software', 'Custom Software / ERP'), ('api', 'API & Integration')], default='web', max_length=50)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('short_description', models.TextField()),
                ('challenge', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('results_summary', models.TextField(blank=True)),
                ('technologies', models.JSONField(default=list, help_text='List of tech used e.g. ["React", "Django", "PostgreSQL"]')),
                ('metrics', models.JSONField(blank=True, default=list, help_text='List of metric dicts e.g. [{"label": "Performance", "value": "+120%"}]')),
                ('featured_image', models.CharField(default='https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1200&auto=format&fit=crop', max_length=255)),
                ('gallery_images', models.JSONField(blank=True, default=list)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
