# Generated by Django 6.1.1 on 2026-09-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('short_description', models.TextField(help_text='Concise summary for homepage and cards')),
                ('full_description', models.TextField(help_text='Detailed overview for service detail page')),
                ('icon_name', models.CharField(default='Code', help_text='Lucide icon name e.g. Globe, Smartphone, Server, Cloud, Cpu, Palette', max_length=50)),
                ('features', models.JSONField(blank=True, default=list, help_text='List of key feature bullets')),
                ('deliverables', models.JSONField(blank=True, default=list, help_text='List of key deliverables')),
                ('tech_stack', models.JSONField(blank=True, default=list, help_text='Associated technologies list')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('industry', models.CharField(default='Cross-Industry', max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('key_modules', models.JSONField(blank=True, default=list, help_text='Key modules or capabilities')),
                ('business_benefits', models.JSONField(blank=True, default=list, help_text='ROI & business values')),
                ('icon_name', models.CharField(default='Layers', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Solution',
                'verbose_name_plural': 'Solutions',
                'ordering': ['order', 'id'],
            },
        ),
    ]
