# Generated by Django 6.1.1 on 2026-09-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General'), ('development', 'Development Process'), ('pricing', 'Pricing & Engagement'), ('support', 'Support & Maintenance')], default='general', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Core Apex.dev', max_length=100)),
                ('tagline', models.CharField(default='Web • App • Cloud • Software Solutions', max_length=255)),
                ('hero_headline', models.CharField(default='We Turn Ideas Into Digital Reality.', max_length=255)),
                ('hero_subheading', models.TextField(default='We build modern websites, mobile applications, cloud platforms and custom software solutions that help businesses grow.')),
                ('email', models.EmailField(default='contact@coreapex.dev', max_length=254)),
                ('phone', models.CharField(default='+91 98765 43210', max_length=50)),
                ('address', models.CharField(default='Tamil Nadu, India', max_length=255)),
                ('founder_name', models.CharField(default='Raja Mohamed', max_length=100)),
                ('founder_role', models.CharField(default='Founder & CEO', max_length=100)),
                ('founder_bio', models.TextField(default='Passionate about building scalable digital products and transforming business visions into high-impact reality.')),
                ('github_url', models.URLField(blank=True, default='https://github.com', null=True)),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com', null=True)),
                ('twitter_url', models.URLField(blank=True, default='https://x.com', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('avatar_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('cloud', 'Cloud & DevOps'), ('api', 'API & Integration')], default='backend', max_length=50)),
                ('icon_name', models.CharField(help_text='Icon identifier e.g. python, django, react', max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_core', models.BooleanField(default=True, help_text='Display in central orbit')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
                'ordering': ['order', 'name'],
            },
        ),
    ]
