# Generated by Django 6.1.1 on 2026-09-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='whatsapp_url',
            field=models.URLField(blank=True, default='https://wa.me/message/THZ4AI7TCFGLE1', null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='address',
            field=models.CharField(default='1/137, L. Karungulam, Ramanathapuram, Tamil Nadu – 623527', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='email',
            field=models.EmailField(default='coreapex.dev@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='phone',
            field=models.CharField(default='+91 7639930013', max_length=50),
        ),
    ]
