# Generated by Django 6.1.1 on 2026-09-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesetting_whatsapp_url_alter_sitesetting_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Upload an image file for this team member (preferred over Avatar URL).', null=True, upload_to='team/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='Optional fallback external image URL (used only if no uploaded Avatar exists).', verbose_name='Avatar URL'),
        ),
    ]
