# Generated by Django 6.1.1 on 2026-09-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('service', models.CharField(choices=[('website', 'Website Development'), ('mobile_app', 'Mobile App Development'), ('ecommerce', 'Ecommerce Platform'), ('custom_software', 'Custom Software Development'), ('crm_erp', 'CRM / ERP Solution'), ('cloud_solution', 'Cloud Solution & Infrastructure'), ('api_dev', 'API Development & Integration'), ('ui_ux', 'UI/UX Design'), ('other', 'Other Custom Requirement')], default='website', max_length=50)),
                ('budget', models.CharField(choices=[('under_5k', '< $5,000 / ₹4,00,000'), ('5k_15k', '$5,000 - $15,000 / ₹4L - ₹12L'), ('15k_50k', '$15,000 - $50,000 / ₹12L - ₹40L'), ('50k_plus', '$50,000+ / ₹40L+ Enterprise'), ('undecided', 'Flexible / Not Sure Yet')], default='5k_15k', max_length=50)),
                ('project_details', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New Lead'), ('contacted', 'Contacted'), ('discussion', 'In Discussion'), ('proposal_sent', 'Proposal Sent'), ('won', 'Won (Closed-Won)'), ('lost', 'Lost (Closed-Lost)')], default='new', max_length=30)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for sales / development team')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Lead',
                'verbose_name_plural': 'Contact Leads (Pipeline)',
                'ordering': ['-created_at'],
            },
        ),
    ]
