# Generated by Django 6.1.1 on 2026-09-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlead',
            name='budget',
            field=models.CharField(choices=[('under_25k', 'Under ₹25,000'), ('25k_50k', '₹25,000 – ₹50,000'), ('50k_1lakh', '₹50,000 – ₹1,00,000'), ('1lakh_plus', '₹1,00,000+'), ('not_sure', 'Not sure yet')], default='25k_50k', max_length=50),
        ),
    ]
